//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_permits
    {
        public int id { get; set; }
        public string organization_name { get; set; }
        public string telephone { get; set; }
        public string mailing_address { get; set; }
        public string authorized_organization_name { get; set; }
        public Nullable<System.DateTime> permit_start_date { get; set; }
        public Nullable<System.DateTime> permit_end_date { get; set; }
        public string number_registered { get; set; }
        public Nullable<int> total_hours { get; set; }
        public Nullable<int> total_hours_worked { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
    }
}
