//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phones
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public Nullable<decimal> number { get; set; }
        public string phone_type { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
