//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class schools
{
    public schools()
    {
        this.staff_by_schools = new HashSet<staff_by_schools>();
        this.users = new HashSet<users>();
    }

    public int id { get; set; }
    public string code { get; set; }
    public string location { get; set; }
    public Nullable<decimal> size { get; set; }
    public string employee_manager { get; set; }
    public string supervisor { get; set; }
    public string name { get; set; }
    public Nullable<decimal> budget { get; set; }
    public Nullable<int> last_payment_code_secuence { get; set; }

    public virtual staff staff { get; set; }
    public virtual ICollection<staff_by_schools> staff_by_schools { get; set; }
    public virtual ICollection<users> users { get; set; }
}
