//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_groups_users
    {
        public int id { get; set; }
        public string group_code { get; set; }
        public string username { get; set; }
    
        public virtual security_groups security_groups { get; set; }
        public virtual users users { get; set; }
    }
}
