//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class security_groups
{
    public security_groups()
    {
        this.security_groups_users = new HashSet<security_groups_users>();
        this.security_permits = new HashSet<security_permits>();
    }

    public int id { get; set; }
    public string group_code { get; set; }
    public string description { get; set; }

    public virtual ICollection<security_groups_users> security_groups_users { get; set; }
    public virtual ICollection<security_permits> security_permits { get; set; }
}
