//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools
    {
        public int id { get; set; }
        public string code { get; set; }
        public string location { get; set; }
        public Nullable<decimal> size { get; set; }
        public string employee_manager { get; set; }
        public string supervisor { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
